/*
 * Narrator: speak the name of the selected key.
 *
 * Each embedded WAV is referenced via its symbol pair (start /
 * end) declared in narrator_assets.h, which is autogenerated by
 * the EMBED_FILES rule. We map HID usage IDs to symbol pointers
 * at runtime and call audio_play_wav(); audio.c's preempting
 * mixer handles overlap by aborting the previous clip.
 *
 * To extend the vocabulary: drop a new XXX.wav into
 * components/narrator/wav/ and add a corresponding entry to the
 * S_CLIPS table below. The EMBED_FILES symbol naming convention
 * is documented in the ESP-IDF build-system docs.
 */

#include "sdkconfig.h"

#if CONFIG_BOARD_HAS_PSRAM && CONFIG_BOARD_HAS_SPEAKER && CONFIG_NARRATOR_ENABLE

#include "narrator.h"

#include <stdint.h>
#include <stddef.h>
#include <string.h>

#include <esp_log.h>

#include "audio.h"
#include "kb_layout.h"

static const char *TAG = "narrator";

/* For each embedded asset the linker exposes
 *   extern const uint8_t _binary_<sanitised_filename>_start[];
 *   extern const uint8_t _binary_<sanitised_filename>_end[];
 * Declare the ones we expect to find under wav/. Missing files
 * cause a link error, which is the desired behaviour -- the
 * user dropped an incomplete asset pack into wav/.
 *
 * Drop-in WAV filenames (mirroring the upstream `audio/` dir):
 *   a.wav .. z.wav, 0.wav .. 9.wav,
 *   space.wav, enter.wav, backspace.wav, tab.wav, escape.wav,
 *   shift.wav, ctrl.wav, alt.wav, altgr.wav, capslock.wav,
 *   apostrophe.wav, backslash.wav, backtick.wav, comma.wav,
 *   equals.wav, lbracket.wav, minus.wav, period.wav,
 *   rbracket.wav, semicolon.wav, slash.wav,
 *   f1.wav .. f12.wav,
 *   insert.wav, home.wav, pageup.wav,
 *   delete.wav, end.wav, pagedown.wav,
 *   up.wav, down.wav, left.wav, right.wav.
 *
 * If you maintain a different vocabulary, edit S_CLIPS below
 * and drop the matching extern declarations.
 *
 * NOTE: these declarations are deliberately *not* `weak`.
 * EMBED_FILES emits each clip as its own object inside
 * libnarrator.a; the final link only pulls an archive member
 * in if it satisfies a strong undefined reference. With weak
 * references the embed objects were silently dropped from the
 * image (~half a megabyte of WAV data missing, firmware grew
 * by only ~20 KB with the narrator enabled). Keeping the refs
 * strong both fixes the size delta and turns missing assets
 * back into a hard link error, as intended.
 */

#define WAV_SYMS(name)                                                \
    extern const uint8_t _binary_##name##_wav_start[];                \
    extern const uint8_t _binary_##name##_wav_end[];

WAV_SYMS(a) WAV_SYMS(b) WAV_SYMS(c) WAV_SYMS(d) WAV_SYMS(e)
WAV_SYMS(f) WAV_SYMS(g) WAV_SYMS(h) WAV_SYMS(i) WAV_SYMS(j)
WAV_SYMS(k) WAV_SYMS(l) WAV_SYMS(m) WAV_SYMS(n) WAV_SYMS(o)
WAV_SYMS(p) WAV_SYMS(q) WAV_SYMS(r) WAV_SYMS(s) WAV_SYMS(t)
WAV_SYMS(u) WAV_SYMS(v) WAV_SYMS(w) WAV_SYMS(x) WAV_SYMS(y)
WAV_SYMS(z)
WAV_SYMS(0) WAV_SYMS(1) WAV_SYMS(2) WAV_SYMS(3) WAV_SYMS(4)
WAV_SYMS(5) WAV_SYMS(6) WAV_SYMS(7) WAV_SYMS(8) WAV_SYMS(9)
WAV_SYMS(space) WAV_SYMS(enter) WAV_SYMS(backspace)
WAV_SYMS(tab)   WAV_SYMS(escape)
WAV_SYMS(shift) WAV_SYMS(ctrl)  WAV_SYMS(alt) WAV_SYMS(altgr)
WAV_SYMS(capslock)
WAV_SYMS(apostrophe) WAV_SYMS(backslash) WAV_SYMS(backtick)
WAV_SYMS(comma) WAV_SYMS(equals) WAV_SYMS(lbracket) WAV_SYMS(minus)
WAV_SYMS(period) WAV_SYMS(rbracket) WAV_SYMS(semicolon) WAV_SYMS(slash)
WAV_SYMS(f1) WAV_SYMS(f2) WAV_SYMS(f3)  WAV_SYMS(f4)  WAV_SYMS(f5)  WAV_SYMS(f6)
WAV_SYMS(f7) WAV_SYMS(f8) WAV_SYMS(f9)  WAV_SYMS(f10) WAV_SYMS(f11) WAV_SYMS(f12)
WAV_SYMS(insert) WAV_SYMS(home)   WAV_SYMS(pageup)
WAV_SYMS(delete) WAV_SYMS(end)    WAV_SYMS(pagedown)
WAV_SYMS(up)     WAV_SYMS(down)   WAV_SYMS(left)    WAV_SYMS(right)

typedef struct {
    uint8_t hid_usage;
    const uint8_t *start;
    const uint8_t *end;
} clip_t;

#define CLIP(usage, name) { (usage), _binary_##name##_wav_start, _binary_##name##_wav_end }

static const clip_t S_CLIPS[] = {
    CLIP(HID_USAGE_A, a), CLIP(HID_USAGE_B, b), CLIP(HID_USAGE_C, c),
    CLIP(HID_USAGE_D, d), CLIP(HID_USAGE_E, e), CLIP(HID_USAGE_F, f),
    CLIP(HID_USAGE_G, g), CLIP(HID_USAGE_H, h), CLIP(HID_USAGE_I, i),
    CLIP(HID_USAGE_J, j), CLIP(HID_USAGE_K, k), CLIP(HID_USAGE_L, l),
    CLIP(HID_USAGE_M, m), CLIP(HID_USAGE_N, n), CLIP(HID_USAGE_O, o),
    CLIP(HID_USAGE_P, p), CLIP(HID_USAGE_Q, q), CLIP(HID_USAGE_R, r),
    CLIP(HID_USAGE_S, s), CLIP(HID_USAGE_T, t), CLIP(HID_USAGE_U, u),
    CLIP(HID_USAGE_V, v), CLIP(HID_USAGE_W, w), CLIP(HID_USAGE_X, x),
    CLIP(HID_USAGE_Y, y), CLIP(HID_USAGE_Z, z),
    CLIP(HID_USAGE_0, 0), CLIP(HID_USAGE_1, 1), CLIP(HID_USAGE_2, 2),
    CLIP(HID_USAGE_3, 3), CLIP(HID_USAGE_4, 4), CLIP(HID_USAGE_5, 5),
    CLIP(HID_USAGE_6, 6), CLIP(HID_USAGE_7, 7), CLIP(HID_USAGE_8, 8),
    CLIP(HID_USAGE_9, 9),
    CLIP(HID_USAGE_SPACE,      space),
    CLIP(HID_USAGE_ENTER,      enter),
    CLIP(HID_USAGE_BACKSPACE,  backspace),
    CLIP(HID_USAGE_TAB,        tab),
    CLIP(HID_USAGE_ESCAPE,     escape),
    CLIP(HID_USAGE_CAPSLOCK,   capslock),
    CLIP(HID_USAGE_GRAVE,      backtick),
    CLIP(HID_USAGE_MINUS,      minus),
    CLIP(HID_USAGE_EQUAL,      equals),
    CLIP(HID_USAGE_LBRACKET,   lbracket),
    CLIP(HID_USAGE_RBRACKET,   rbracket),
    CLIP(HID_USAGE_BACKSLASH,  backslash),
    CLIP(HID_USAGE_SEMICOLON,  semicolon),
    CLIP(HID_USAGE_APOSTROPHE, apostrophe),
    CLIP(HID_USAGE_COMMA,      comma),
    CLIP(HID_USAGE_PERIOD,     period),
    CLIP(HID_USAGE_SLASH,      slash),
    CLIP(HID_USAGE_F1,  f1),  CLIP(HID_USAGE_F2,  f2),  CLIP(HID_USAGE_F3,  f3),
    CLIP(HID_USAGE_F4,  f4),  CLIP(HID_USAGE_F5,  f5),  CLIP(HID_USAGE_F6,  f6),
    CLIP(HID_USAGE_F7,  f7),  CLIP(HID_USAGE_F8,  f8),  CLIP(HID_USAGE_F9,  f9),
    CLIP(HID_USAGE_F10, f10), CLIP(HID_USAGE_F11, f11), CLIP(HID_USAGE_F12, f12),
    CLIP(HID_USAGE_INSERT,    insert),
    CLIP(HID_USAGE_HOME,      home),
    CLIP(HID_USAGE_PAGEUP,    pageup),
    CLIP(HID_USAGE_DELETE,    delete),
    CLIP(HID_USAGE_END,       end),
    CLIP(HID_USAGE_PAGEDOWN,  pagedown),
    CLIP(HID_USAGE_UP,    up),
    CLIP(HID_USAGE_DOWN,  down),
    CLIP(HID_USAGE_LEFT,  left),
    CLIP(HID_USAGE_RIGHT, right),
};

/* Modifier keys (Shift / Ctrl / Alt / Win / AGr) all carry
 * HID_USAGE_NONE in the layout because they are tracked locally
 * as sticky modifier latches rather than sent on press. They are
 * distinguished by the cell's label string. */
typedef struct {
    const char *label;
    const uint8_t *start;
    const uint8_t *end;
} mod_clip_t;

#define MOD_CLIP(lbl, name) { (lbl), _binary_##name##_wav_start, _binary_##name##_wav_end }

static const mod_clip_t S_MOD_CLIPS[] = {
    MOD_CLIP("Sft", shift),
    MOD_CLIP("Ctl", ctrl),
    MOD_CLIP("Alt", alt),
    MOD_CLIP("AGr", altgr),
    /* No upstream clip for "Win" / "Cmd"; fall back to silence. */
};

static const clip_t *find_clip(uint8_t usage)
{
    for (size_t i = 0; i < sizeof(S_CLIPS) / sizeof(S_CLIPS[0]); ++i) {
        if (S_CLIPS[i].hid_usage == usage && S_CLIPS[i].start) {
            return &S_CLIPS[i];
        }
    }
    return NULL;
}

void narrator_init(void)
{
    audio_init();
    audio_set_volume(CONFIG_AUDIO_VOLUME);
    ESP_LOGI(TAG, "ready (volume %d%%)", CONFIG_AUDIO_VOLUME);
}

void narrator_speak_hid(unsigned hid_usage)
{
    const clip_t *c = find_clip((uint8_t)hid_usage);
    if (!c) return;
    audio_play_wav(c->start, (size_t)(c->end - c->start));
}

void narrator_speak_key(const kb_key_t *k)
{
    if (!k) return;
    if (k->hid_usage != HID_USAGE_NONE) {
        narrator_speak_hid(k->hid_usage);
        return;
    }
    /* HID_USAGE_NONE: modifier key tracked locally. Dispatch by
     * the cell's idle label so Shift / Ctrl / Alt / AGr each get
     * their own clip. Empty / spacer cells (label "") fall
     * through to silence. */
    const char *lbl = k->label_unshifted;
    if (!lbl || !*lbl) return;
    for (size_t i = 0; i < sizeof(S_MOD_CLIPS) / sizeof(S_MOD_CLIPS[0]); ++i) {
        if (strcmp(S_MOD_CLIPS[i].label, lbl) == 0) {
            audio_play_wav(S_MOD_CLIPS[i].start,
                           (size_t)(S_MOD_CLIPS[i].end - S_MOD_CLIPS[i].start));
            return;
        }
    }
}

void narrator_speak_selection(void)
{
    /* keyboard_ui_press_current() is the BLE path; here we just
     * resolve the selected key and speak it. The dependency on
     * keyboard_ui is expressed via weak symbols so narrator stays
     * stand-alone-usable. We prefer the richer kb_key_t* getter
     * when present (covers modifiers), falling back to the older
     * HID-only getter for compatibility. */
    extern const kb_key_t *keyboard_ui_selected_key(void) __attribute__((weak));
    extern int keyboard_ui_selected_hid_usage(void) __attribute__((weak));
    if (keyboard_ui_selected_key) {
        narrator_speak_key(keyboard_ui_selected_key());
        return;
    }
    if (keyboard_ui_selected_hid_usage) {
        narrator_speak_hid((unsigned)keyboard_ui_selected_hid_usage());
    }
}

#endif /* PSRAM && SPEAKER && NARRATOR_ENABLE */
