/*
 * Narrator: speak the name of the selected key.
 *
 * Each embedded WAV is referenced via its symbol pair (start /
 * end) declared in narrator_assets.h, which is autogenerated by
 * the EMBED_FILES rule. We map HID usage IDs to symbol pointers
 * at runtime and call audio_play_wav(); audio.c's preempting
 * mixer handles overlap by aborting the previous clip.
 *
 * To extend the vocabulary: drop a new XXX.wav into
 * components/narrator/wav/ and add a corresponding entry to the
 * S_CLIPS table below. The EMBED_FILES symbol naming convention
 * is documented in the ESP-IDF build-system docs.
 */

#include "sdkconfig.h"

#if CONFIG_BOARD_HAS_PSRAM && CONFIG_BOARD_HAS_SPEAKER && CONFIG_NARRATOR_ENABLE

#include "narrator.h"

#include <stdint.h>
#include <stddef.h>
#include <string.h>

#include <esp_log.h>

#include "audio.h"
#include "kb_layout.h"

static const char *TAG = "narrator";

/* For each embedded asset the linker exposes
 *   extern const uint8_t _binary_<sanitised_filename>_start[];
 *   extern const uint8_t _binary_<sanitised_filename>_end[];
 * Declare the ones we expect to find under wav/. Missing files
 * cause a link error, which is the desired behaviour -- the
 * user dropped an incomplete asset pack into wav/.
 *
 * Drop-in WAV filenames (mirroring the upstream `audio/` dir):
 *   a.wav .. z.wav, 0.wav .. 9.wav,
 *   space.wav, enter.wav, backspace.wav, tab.wav, escape.wav,
 *   shift.wav, ctrl.wav, alt.wav.
 *
 * If you maintain a different vocabulary, edit S_CLIPS below
 * and drop the matching extern declarations.
 *
 * NOTE: these declarations are deliberately *not* `weak`.
 * EMBED_FILES emits each clip as its own object inside
 * libnarrator.a; the final link only pulls an archive member
 * in if it satisfies a strong undefined reference. With weak
 * references the embed objects were silently dropped from the
 * image (~half a megabyte of WAV data missing, firmware grew
 * by only ~20 KB with the narrator enabled). Keeping the refs
 * strong both fixes the size delta and turns missing assets
 * back into a hard link error, as intended.
 */

#define WAV_SYMS(name)                                                \
    extern const uint8_t _binary_##name##_wav_start[];                \
    extern const uint8_t _binary_##name##_wav_end[];

WAV_SYMS(a) WAV_SYMS(b) WAV_SYMS(c) WAV_SYMS(d) WAV_SYMS(e)
WAV_SYMS(f) WAV_SYMS(g) WAV_SYMS(h) WAV_SYMS(i) WAV_SYMS(j)
WAV_SYMS(k) WAV_SYMS(l) WAV_SYMS(m) WAV_SYMS(n) WAV_SYMS(o)
WAV_SYMS(p) WAV_SYMS(q) WAV_SYMS(r) WAV_SYMS(s) WAV_SYMS(t)
WAV_SYMS(u) WAV_SYMS(v) WAV_SYMS(w) WAV_SYMS(x) WAV_SYMS(y)
WAV_SYMS(z)
WAV_SYMS(space) WAV_SYMS(enter) WAV_SYMS(backspace)
WAV_SYMS(tab)   WAV_SYMS(escape)
WAV_SYMS(shift) WAV_SYMS(ctrl)  WAV_SYMS(alt)

typedef struct {
    uint8_t hid_usage;
    const uint8_t *start;
    const uint8_t *end;
} clip_t;

#define CLIP(usage, name) { (usage), _binary_##name##_wav_start, _binary_##name##_wav_end }

static const clip_t S_CLIPS[] = {
    CLIP(HID_USAGE_A, a), CLIP(HID_USAGE_B, b), CLIP(HID_USAGE_C, c),
    CLIP(HID_USAGE_D, d), CLIP(HID_USAGE_E, e), CLIP(HID_USAGE_F, f),
    CLIP(HID_USAGE_G, g), CLIP(HID_USAGE_H, h), CLIP(HID_USAGE_I, i),
    CLIP(HID_USAGE_J, j), CLIP(HID_USAGE_K, k), CLIP(HID_USAGE_L, l),
    CLIP(HID_USAGE_M, m), CLIP(HID_USAGE_N, n), CLIP(HID_USAGE_O, o),
    CLIP(HID_USAGE_P, p), CLIP(HID_USAGE_Q, q), CLIP(HID_USAGE_R, r),
    CLIP(HID_USAGE_S, s), CLIP(HID_USAGE_T, t), CLIP(HID_USAGE_U, u),
    CLIP(HID_USAGE_V, v), CLIP(HID_USAGE_W, w), CLIP(HID_USAGE_X, x),
    CLIP(HID_USAGE_Y, y), CLIP(HID_USAGE_Z, z),
    CLIP(HID_USAGE_SPACE,     space),
    CLIP(HID_USAGE_ENTER,     enter),
    CLIP(HID_USAGE_BACKSPACE, backspace),
    CLIP(HID_USAGE_TAB,       tab),
    CLIP(HID_USAGE_ESCAPE,    escape),
};

static const clip_t *find_clip(uint8_t usage)
{
    for (size_t i = 0; i < sizeof(S_CLIPS) / sizeof(S_CLIPS[0]); ++i) {
        if (S_CLIPS[i].hid_usage == usage && S_CLIPS[i].start) {
            return &S_CLIPS[i];
        }
    }
    return NULL;
}

void narrator_init(void)
{
    audio_init();
    audio_set_volume(CONFIG_AUDIO_VOLUME);
    ESP_LOGI(TAG, "ready (volume %d%%)", CONFIG_AUDIO_VOLUME);
}

void narrator_speak_hid(unsigned hid_usage)
{
    const clip_t *c = find_clip((uint8_t)hid_usage);
    if (!c) return;
    audio_play_wav(c->start, (size_t)(c->end - c->start));
}

void narrator_speak_selection(void)
{
    /* keyboard_ui_press_current() is the BLE path; here we just
     * resolve the selected key's HID usage and speak it. */
    /* The currently selected cell lives in keyboard_ui, which we
     * don't want a hard dependency on (narrator would then be
     * impossible to use stand-alone). Instead the input_router
     * passes us the selection via this entry point at every
     * navigation event; we re-read the active layout's cursor
     * from the UI through a tiny weak helper. */
    extern int keyboard_ui_selected_hid_usage(void) __attribute__((weak));
    if (!keyboard_ui_selected_hid_usage) return;
    narrator_speak_hid((unsigned)keyboard_ui_selected_hid_usage());
}

#endif /* PSRAM && SPEAKER && NARRATOR_ENABLE */
